version: '3'

services:
  app:
    image: beckjiang/chatgpt-api
    container_name: chatgpt_api
    restart: unless-stopped
    ports:
      - '8082:8082'
    volumes:
      - ./config:/app/config
    environment:
      CHATGPT_BASE_URL: https://ai.fakeopen.com/api/
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5